#Requires -Version 5.1
<#
  Download the video-model stack (MiniMax H3 + LTX-2.5, most-downloaded official
  repos, 8GB-friendly int8/nvfp4 quants) into repo-root/models/ (git-ignored),
  then wire it up via tmp/ComfyUI/extra_model_paths.yaml.

  Run from the repo root:  powershell -ExecutionPolicy Bypass -File scripts/Download-Models.ps1
  Needs: tmp/ComfyUI/venv from scripts/Install.ps1. No hf CLI needed (uses the
  venv's huggingface_hub). Gated repos (Lightricks/LTX-2.5) need access first:
  open https://huggingface.co/Lightricks/LTX-2.5 in a browser, click
  "Agree and Access", then set $env:HF_TOKEN to a token from
  https://huggingface.co/settings/tokens before running this script.
  Downloads are resumable - just re-run if interrupted. Total ~86 GB.
#>
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$VenvPy = "tmp/ComfyUI/venv/Scripts/python.exe"
if (-not (Test-Path $VenvPy)) { Write-Error "venv not found. Run scripts/Install.ps1 first." }
New-Item -ItemType Directory -Force "models" | Out-Null

function Get-RepoFiles($RepoId, $Patterns) {
  Write-Host "`n=== $RepoId ===" -ForegroundColor Cyan
  $patJson = ($Patterns | ForEach-Object { '"' + $_ + '"' }) -join ","
  $code = "from huggingface_hub import snapshot_download; snapshot_download(repo_id='$RepoId', local_dir='models', allow_patterns=[$patJson])"
  & $VenvPy -c $code
}

# --- MiniMax H3 (official ComfyUI repack; template video_minimax_h3_t2v needs exactly these) ---
Get-RepoFiles "Comfy-Org/MiniMax-H3" @(
  "diffusion_models/minimax_h3_fl2va_pruned_int8_convrot.safetensors",
  "text_encoders/qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors",
  "vae/minimax_h3_video_vae_fp16.safetensors",
  "vae/minimax_h3_audio_vae_fp32.safetensors",
  "loras/minimax_h3_fl2v_turbo_4step_v1.0_768p_comfyui_bf16.safetensors"
)
# 8-step turbo LoRA lives at repo root of lightx2v/Minimax-h3-Turbo (template default) -> move into loras/
Get-RepoFiles "lightx2v/Minimax-h3-Turbo" @(
  "minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors"
)
if (Test-Path "models/minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors") {
  Move-Item -Force "models/minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors" "models/loras/"
}

# --- LTX-2.5 (official; distilled + comfy-int8, conv VAE, spatial upscaler for multi-stage) ---
Get-RepoFiles "Lightricks/LTX-2.5" @(
  "diffusion_models/ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors",
  "text_encoders/gemma4-12b-with-proj-ltx-2.5-comfy-int8-convrot.safetensors",
  "vae/ltx-2.5-video-vae-conv-bf16.safetensors",
  "vae/ltx-2.5-audio-vae-bf16.safetensors",
  "latent_upscale_models/ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors",
  "model_patches/ltx-2.5-duration-head-bf16.safetensors"
)

# --- Wire into ComfyUI (machine-local absolute base_path, regenerated per machine) ---
$base = ($RepoRoot -replace "\\", "/")
@"
# Generated by scripts/Download-Models.ps1 - do not hand-edit, re-run the script.
comfyui_video_models:
    base_path: $base
    diffusion_models: models/diffusion_models/
    text_encoders: models/text_encoders/
    vae: models/vae/
    loras: models/loras/
    latent_upscale_models: models/latent_upscale_models/
    model_patches: models/model_patches/
"@ | Out-File -Encoding utf8 "tmp/ComfyUI/extra_model_paths.yaml"

Write-Host "`n=== models/ ===" -ForegroundColor Cyan
Get-ChildItem -Recurse -File "models" | ForEach-Object { "{0,8:N1} GB  {1}" -f ($_.Length / 1e9), $_.FullName.Substring($RepoRoot.Length + 1) }
Write-Host "`nDone. Restart ComfyUI (scripts/Start.ps1) so it picks up the new paths." -ForegroundColor Green
